let irregular_verbs = [
    [{"en": ["bet", "bet", "bet"], "_": ["bet", "bet", "bet"], "ru": "держать пари"},
        {"en": ["bid (делать ставку)", "bid", "bid"], "_": ["bɪd", "bɪd", "bɪd"], "ru": "предлагать цену, торговаться"},
        {
            "en": ["broadcast", "broadcast", "broadcast"],
            "_": ["ˈbrɔːd.kɑːst", "ˈbrɔːd.kɑːst", "ˈbrɔːd.kɑːst"],
            "ru": "транслировать"
        },
        {"en": ["burst", "burst", "burst"], "_": ["bɜːrst", "bɜːrst", "bɜːrst"], "ru": "взрываться"},
        {"en": ["cast", "cast", "cast"], "_": ["kɑːst", "kɑːst", "kɑːst"], "ru": "бросать, лить (металл)"},
        {"en": ["cost", "cost", "cost"], "_": ["kɒst", "kɒst", "kɒst"], "ru": "стоить"},
        {"en": ["cut", "cut", "cut"], "_": ["kʌt", "kʌt", "kʌt"], "ru": "резать"},
        {"en": ["fit", "fit", "fit"], "_": ["fɪt", "fɪt", "fɪt"], "ru": "подходить по размеру"},
        {"en": ["hit", "hit", "hit"], "_": ["hɪt", "hɪt", "hɪt"], "ru": "ударять"},
        {"en": ["hurt", "hurt", "hurt"], "_": ["hɜːrt", "hɜːrt", "hɜːrt"], "ru": "причинять боль"},
        {"en": ["let", "let", "let"], "_": ["let", "let", "let"], "ru": "позволять"},
        {"en": ["put", "put", "put"], "_": ["pʊt", "pʊt", "pʊt"], "ru": "класть"},
        {"en": ["quit", "quit", "quit"], "_": ["kwɪt", "kwɪt", "kwɪt"], "ru": "бросать, прекращать"},
        {
            "en": ["read", "read", "read"],
            "_": ["riːd", "red", "red"],
            "ru": "читать (произношение меняется, написание нет)"
        },
        {"en": ["set", "set", "set"], "_": ["set", "set", "set"], "ru": "устанавливать"},
        {"en": ["shed", "shed", "shed"], "_": ["ʃed", "ʃed", "ʃed"], "ru": "проливать (слезы), сбрасывать (кожу)"},
        {"en": ["shut", "shut", "shut"], "_": ["ʃʌt", "ʃʌt", "ʃʌt"], "ru": "закрывать"},
        {"en": ["slit", "slit", "slit"], "_": ["slɪt", "slɪt", "slɪt"], "ru": "прорезать"},
        {"en": ["split", "split", "split"], "_": ["splɪt", "splɪt", "splɪt"], "ru": "раскалывать(ся)"},
        {"en": ["spread", "spread", "spread"], "_": ["spred", "spred", "spred"], "ru": "распространять(ся)"},
        {"en": ["thrust", "thrust", "thrust"], "_": ["θrʌst", "θrʌst", "θrʌst"], "ru": "толкать, совать"},
        {"en": ["upset", "upset", "upset"], "_": ["ʌpˈset", "ʌpˈset", "ʌpˈset"], "ru": "огорчать, расстраивать"},
        {"en": ["bend", "bent", "bent"], "_": ["bend", "bent", "bent"], "ru": "сгибать(ся)"},
        {"en": ["bring", "brought", "brought"], "_": ["brɪŋ", "brɔːt", "brɔːt"], "ru": "приносить"},
        {"en": ["build", "built", "built"], "_": ["bɪld", "bɪlt", "bɪlt"], "ru": "строить"},
        {"en": ["burn", "burnt/burned", "burnt/burned"], "_": ["bɜːrn", "bɜːrnt", "bɜːrnt"], "ru": "гореть, жечь"},
        {"en": ["buy", "bought", "bought"], "_": ["baɪ", "bɔːt", "bɔːt"], "ru": "покупать"},
        {"en": ["catch", "caught", "caught"], "_": ["kætʃ", "kɔːt", "kɔːt"], "ru": "ловить"},
        {"en": ["creep", "crept", "crept"], "_": ["kriːp", "krept", "krept"], "ru": "ползать, красться"},
        {"en": ["deal", "dealt", "dealt"], "_": ["diːl", "delt", "delt"], "ru": "иметь дело, распределять"},
        {"en": ["dig", "dug", "dug"], "_": ["dɪɡ", "dʌɡ", "dʌɡ"], "ru": "копать"},
        {
            "en": ["dream", "dreamt/dreamed", "dreamt/dreamed"],
            "_": ["driːm", "dremt", "dremt"],
            "ru": "мечтать, видеть сны"
        },
        {"en": ["feed", "fed", "fed"], "_": ["fiːd", "fed", "fed"], "ru": "кормить"},
        {"en": ["feel", "felt", "felt"], "_": ["fiːl", "felt", "felt"], "ru": "чувствовать"},
        {"en": ["fight", "fought", "fought"], "_": ["faɪt", "fɔːt", "fɔːt"], "ru": "бороться, сражаться"},
        {"en": ["find", "found", "found"], "_": ["faɪnd", "faʊnd", "faʊnd"], "ru": "находить"},
        {"en": ["flee", "fled", "fled"], "_": ["fliː", "fled", "fled"], "ru": "спасаться бегством"},
        {"en": ["get", "got", "got (британский)/gotten (американский)"], "_": ["ɡet", "ɡɒt", "ɡɒt"], "ru": "получать"},
        {"en": ["hang (вешать)", "hung", "hung"], "_": ["hæŋ", "hʌŋ", "hʌŋ"], "ru": "вешать"},
        {"en": ["have", "had", "had"], "_": ["hæv", "hæd", "hæd"], "ru": "иметь"},
        {"en": ["hear", "heard", "heard"], "_": ["hɪər", "hɜːrd", "hɜːrd"], "ru": "слышать"},
        {"en": ["hold", "held", "held"], "_": ["həʊld", "held", "held"], "ru": "держать"},
        {"en": ["keep", "kept", "kept"], "_": ["kiːp", "kept", "kept"], "ru": "хранить, содержать"},
        {"en": ["lay", "laid", "laid"], "_": ["leɪ", "leɪd", "leɪd"], "ru": "класть, стелить"},
        {"en": ["lead", "led", "led"], "_": ["liːd", "led", "led"], "ru": "вести"},
        {"en": ["lean", "leant/leaned", "leant/leaned"], "_": ["liːn", "lent", "lent"], "ru": "наклоняться"},
        {"en": ["learn", "learnt/learned", "learnt/learned"], "_": ["lɜːrn", "lɜːrnt", "lɜːrnt"], "ru": "учить"},
        {"en": ["leave", "left", "left"], "_": ["liːv", "left", "left"], "ru": "покидать, оставлять"},
        {"en": ["lend", "lent", "lent"], "_": ["lend", "lent", "lent"], "ru": "одалживать (давать в долг)"},
        {"en": ["light", "lit/lighted", "lit/lighted"], "_": ["laɪt", "lɪt", "lɪt"], "ru": "зажигать"},
        {"en": ["lose", "lost", "lost"], "_": ["luːz", "lɒst", "lɒst"], "ru": "терять"},
        {"en": ["make", "made", "made"], "_": ["meɪk", "meɪd", "meɪd"], "ru": "делать, создавать"},
        {"en": ["mean", "meant", "meant"], "_": ["miːn", "ment", "ment"], "ru": "значить, иметь в виду"},
        {"en": ["meet", "met", "met"], "_": ["miːt", "met", "met"], "ru": "встречать"},
        {"en": ["pay", "paid", "paid"], "_": ["peɪ", "peɪd", "peɪd"], "ru": "платить"},
        {"en": ["say", "said", "said"], "_": ["seɪ", "sed", "sed"], "ru": "говорить"},
        {"en": ["seek", "sought", "sought"], "_": ["siːk", "sɔːt", "sɔːt"], "ru": "искать"},
        {"en": ["sell", "sold", "sold"], "_": ["sel", "səʊld", "səʊld"], "ru": "продавать"},
        {"en": ["send", "sent", "sent"], "_": ["send", "sent", "sent"], "ru": "посылать"},
        {"en": ["shine (светить)", "shone", "shone"], "_": ["ʃaɪn", "ʃɒn", "ʃɒn"], "ru": "светить"},
        {"en": ["shoot", "shot", "shot"], "_": ["ʃuːt", "ʃɒt", "ʃɒt"], "ru": "стрелять"},
        {"en": ["sit", "sat", "sat"], "_": ["sɪt", "sæt", "sæt"], "ru": "сидеть"},
        {"en": ["sleep", "slept", "slept"], "_": ["sliːp", "slept", "slept"], "ru": "спать"},
        {"en": ["slide", "slid", "slid"], "_": ["slaɪd", "slɪd", "slɪd"], "ru": "скользить"},
        {"en": ["sling", "slung", "slung"], "_": ["slɪŋ", "slʌŋ", "slʌŋ"], "ru": "швырять, вешать через плечо"},
        {"en": ["smell", "smelt/smelled", "smelt/smelled"], "_": ["smel", "smelt", "smelt"], "ru": "нюхать, пахнуть"},
        {"en": ["speed", "sped/speeded", "sped/speeded"], "_": ["spiːd", "sped", "sped"], "ru": "ускорять(ся)"},
        {
            "en": ["spell", "spelt/spelled", "spelt/spelled"],
            "_": ["spel", "spelt", "spelt"],
            "ru": "писать или произносить по буквам"
        },
        {"en": ["spend", "spent", "spent"], "_": ["spend", "spent", "spent"], "ru": "тратить"},
        {"en": ["spill", "spilt/spilled", "spilt/spilled"], "_": ["spɪl", "spɪlt", "spɪlt"], "ru": "проливать"},
        {"en": ["spin", "spun", "spun"], "_": ["spɪn", "spʌn", "spʌn"], "ru": "вращать(ся)"},
        {"en": ["spit", "spat", "spat"], "_": ["spɪt", "spæt", "spæt"], "ru": "плевать"},
        {"en": ["spoil", "spoilt/spoiled", "spoilt/spoiled"], "_": ["spɔɪl", "spɔɪlt", "spɔɪlt"], "ru": "портить"},
        {"en": ["stand", "stood", "stood"], "_": ["stænd", "stʊd", "stʊd"], "ru": "стоять"},
        {"en": ["stick", "stuck", "stuck"], "_": ["stɪk", "stʌk", "stʌk"], "ru": "приклеивать, воткнуть"},
        {"en": ["sting", "stung", "stung"], "_": ["stɪŋ", "stʌŋ", "stʌŋ"], "ru": "жалить"},
        {"en": ["strike", "struck", "struck"], "_": ["straɪk", "strʌk", "strʌk"], "ru": "ударять, бастовать"},
        {"en": ["sweep", "swept", "swept"], "_": ["swiːp", "swept", "swept"], "ru": "подметать"},
        {"en": ["swing", "swung", "swung"], "_": ["swɪŋ", "swʌŋ", "swʌŋ"], "ru": "качать(ся)"},
        {"en": ["teach", "taught", "taught"], "_": ["tiːtʃ", "tɔːt", "tɔːt"], "ru": "учить, преподавать"},
        {"en": ["tell", "told", "told"], "_": ["tel", "təʊld", "təʊld"], "ru": "рассказывать"},
        {"en": ["think", "thought", "thought"], "_": ["θɪŋk", "θɔːt", "θɔːt"], "ru": "думать"},
        {
            "en": ["understand", "understood", "understood"],
            "_": ["ˌʌn.dərˈstænd", "ˌʌn.dərˈstʊd", "ˌʌn.dərˈstʊd"],
            "ru": "понимать"
        },
        {"en": ["win", "won", "won"], "_": ["wɪn", "wʌn", "wʌn"], "ru": "выигрывать"},
        {"en": ["wind", "wound", "wound"], "_": ["waɪnd", "waʊnd", "waʊnd"], "ru": "заводить (механизм), извиваться"},
        {"en": ["awake", "awoke", "awoken"], "_": ["əˈweɪk", "əˈwəʊk", "əˈwəʊ.kən"], "ru": "пробуждать(ся)"},
        {"en": ["bear", "bore", "born/borne"], "_": ["beər", "bɔːr", "bɔːrn"], "ru": "рожать, выносить"},
        {"en": ["beat", "beat", "beaten"], "_": ["biːt", "biːt", "ˈbiː.tən"], "ru": "бить"},
        {"en": ["begin", "began", "begun"], "_": ["bɪˈɡɪn", "bɪˈɡæn", "bɪˈɡʌn"], "ru": "начинать(ся)"},
        {"en": ["bite", "bit", "bitten"], "_": ["baɪt", "bɪt", "ˈbɪt.ən"], "ru": "кусать"},
        {"en": ["blow", "blew", "blown"], "_": ["bləʊ", "bluː", "bləʊn"], "ru": "дуть"},
        {"en": ["break", "broke", "broken"], "_": ["breɪk", "brəʊk", "ˈbrəʊ.kən"], "ru": "ломать"},
        {"en": ["choose", "chose", "chosen"], "_": ["tʃuːz", "tʃəʊz", "ˈtʃəʊ.zən"], "ru": "выбирать"},
        {"en": ["do", "did", "done"], "_": ["duː", "dɪd", "dʌn"], "ru": "делать"},
        {"en": ["draw", "drew", "drawn"], "_": ["drɔː", "druː", "drɔːn"], "ru": "рисовать, тащить"},
        {"en": ["drink", "drank", "drunk"], "_": ["drɪŋk", "dræŋk", "drʌŋk"], "ru": "пить"},
        {"en": ["drive", "drove", "driven"], "_": ["draɪv", "drəʊv", "ˈdrɪv.ən"], "ru": "водить (машину)"},
        {"en": ["eat", "ate", "eaten"], "_": ["iːt", "et,", "ˈiː.tən"], "ru": "есть, кушать"},
        {"en": ["fall", "fell", "fallen"], "_": ["fɔːl", "fel", "ˈfɔː.lən"], "ru": "падать"},
        {"en": ["fly", "flew", "flown"], "_": ["flaɪ", "fluː", "fləʊn"], "ru": "летать"},
        {"en": ["forbid", "forbade", "forbidden"], "_": ["fəˈbɪd", "fəˈbæd", "fəˈbɪd.ən"], "ru": "запрещать"},
        {"en": ["forget", "forgot", "forgotten"], "_": ["fərˈɡet", "fərˈɡɒt", "fərˈɡɒt.ən"], "ru": "забывать"},
        {"en": ["forgive", "forgave", "forgiven"], "_": ["fərˈɡɪv", "fərˈɡeɪv", "fərˈɡɪv.ən"], "ru": "прощать"},
        {"en": ["freeze", "froze", "frozen"], "_": ["friːz", "frəʊz", "ˈfrəʊ.zən"], "ru": "замерзать"},
        {"en": ["give", "gave", "given"], "_": ["ɡɪv", "ɡeɪv", "ˈɡɪv.ən"], "ru": "давать"},
        {"en": ["go", "went", "gone"], "_": ["ɡəʊ", "went", "ɡɒn"], "ru": "идти"},
        {"en": ["grow", "grew", "grown"], "_": ["ɡrəʊ", "ɡruː", "ɡrəʊn"], "ru": "расти, выращивать"},
        {"en": ["hide", "hid", "hidden"], "_": ["haɪd", "hɪd", "ˈhɪd.ən"], "ru": "прятать(ся)"},
        {"en": ["know", "knew", "known"], "_": ["nəʊ", "njuː", "nəʊn"], "ru": "знать"},
        {"en": ["lie (лежать)", "lay", "lain"], "_": ["laɪ", "leɪ", "leɪn"], "ru": "лежать"},
        {"en": ["mistake", "mistook", "mistaken"], "_": ["mɪˈsteɪk", "mɪˈstʊk", "mɪˈsteɪ.kən"], "ru": "ошибаться"},
        {"en": ["ride", "rode", "ridden"], "_": ["raɪd", "rəʊd", "ˈrɪd.ən"], "ru": "ехать верхом"},
        {"en": ["ring", "rang", "rung"], "_": ["rɪŋ", "ræŋ", "rʌŋ"], "ru": "звонить"},
        {"en": ["rise", "rose", "risen"], "_": ["raɪz", "rəʊz", "ˈrɪz.ən"], "ru": "подниматься"},
        {"en": ["see", "saw", "seen"], "_": ["siː", "sɔː", "siːn"], "ru": "видеть"},
        {"en": ["shake", "shook", "shaken"], "_": ["ʃeɪk", "ʃʊk", "ˈʃeɪ.kən"], "ru": "трясти"},
        {"en": ["show", "showed", "shown"], "_": ["ʃəʊ", "ʃəʊd", "ʃəʊn"], "ru": "показывать"},
        {"en": ["shrink", "shrank", "shrunk"], "_": ["ʃrɪŋk", "ʃræŋk", "ʃrʌŋk"], "ru": "сжиматься, садиться (о ткани)"},
        {"en": ["sing", "sang", "sung"], "_": ["sɪŋ", "sæŋ", "sʌŋ"], "ru": "петь"},
        {"en": ["sink", "sank", "sunk"], "_": ["sɪŋk", "sæŋk", "sʌŋk"], "ru": "тонуть, погружаться"},
        {"en": ["speak", "spoke", "spoken"], "_": ["spiːk", "spəʊk", "ˈspəʊ.kən"], "ru": "говорить"},
        {"en": ["spring", "sprang", "sprung"], "_": ["sprɪŋ", "spræŋ", "sprʌŋ"], "ru": "прыгать, возникать"},
        {"en": ["steal", "stole", "stolen"], "_": ["stiːl", "stəʊl", "ˈstəʊ.lən"], "ru": "красть"},
        {"en": ["strive", "strove", "striven"], "_": ["straɪv", "strəʊv", "ˈstrɪv.ən"], "ru": "стремиться"},
        {"en": ["swear", "swore", "sworn"], "_": ["sweər", "swɔːr", "swɔːrn"], "ru": "клясться, ругаться"},
        {"en": ["swim", "swam", "swum"], "_": ["swɪm", "swæm", "swʌm"], "ru": "плавать"},
        {"en": ["take", "took", "taken"], "_": ["teɪk", "tʊk", "ˈteɪ.kən"], "ru": "брать"},
        {"en": ["tear", "tore", "torn"], "_": ["teər", "tɔːr", "tɔːrn"], "ru": "рвать"},
        {"en": ["throw", "threw", "thrown"], "_": ["θrəʊ", "θruː", "θrəʊn"], "ru": "бросать"},
        {"en": ["wake", "woke", "woken"], "_": ["weɪk", "wəʊk", "ˈwəʊ.kən"], "ru": "просыпаться"},
        {"en": ["wear", "wore", "worn"], "_": ["weər", "wɔːr", "wɔːrn"], "ru": "носить (одежду)"},
        {"en": ["weave", "wove", "woven"], "_": ["wiːv", "wəʊv", "ˈwəʊ.vən"], "ru": "ткать"},
        {
            "en": ["withdraw", "withdrew", "withdrawn"],
            "_": ["wɪðˈdrɔː", "wɪðˈdruː", "wɪðˈdrɔːn"],
            "ru": "отзывать, снимать (деньги)"
        },
        {"en": ["write", "wrote", "written"], "_": ["raɪt", "rəʊt", "ˈrɪt.ən"], "ru": "писать"},
        {"en": ["be", "was/were", "been"], "_": ["biː", "wɒz, wɜːr", "biːn"], "ru": "быть, находиться"},
        {"en": ["come", "came", "come"], "_": ["kʌm", "keɪm", "kʌm"], "ru": "приходить"},
        {"en": ["run", "ran", "run"], "_": ["rʌn", "ræn", "rʌn"], "ru": "бежать"},
        {"en": ["arise", "arose", "arisen"], "_": ["əˈraɪz", "əˈrəʊz", "əˈrɪz.ən"], "ru": "возникать"},
        {"en": ["become", "became", "become"], "_": ["bɪˈkʌm", "bɪˈkeɪm", "bɪˈkʌm"], "ru": "становиться"},
        {
            "en": ["befall", "befell", "befallen"],
            "_": ["bɪˈfɔːl", "bɪˈfel", "bɪˈfɔː.lən"],
            "ru": "случаться (часто о плохом)"
        },
        {
            "en": ["beget", "begot", "begotten"],
            "_": ["bɪˈɡet", "bɪˈɡɒt", "bɪˈɡɒt.ən"],
            "ru": "порождать (устар., библ.)"
        },
        {
            "en": ["begin", "began", "begun"],
            "_": ["bɪˈɡɪn", "bɪˈɡæn", "bɪˈɡʌn"],
            "ru": "начинать(ся) (повтор для группы)"
        },
        {"en": ["bend", "bent", "bent"], "_": ["bend", "bent", "bent"], "ru": "сгибать(ся) (повтор для группы)"},
        {"en": ["bind", "bound", "bound"], "_": ["baɪnd", "baʊnd", "baʊnd"], "ru": "связывать"},
        {"en": ["bleed", "bled", "bled"], "_": ["bliːd", "bled", "bled"], "ru": "кровоточить"},
        {"en": ["bless", "blessed/blest", "blessed/blest"], "_": ["bles", "blest", "blest"], "ru": "благословлять"},
        {"en": ["blow", "blew", "blown"], "_": ["bləʊ", "bluː", "bləʊn"], "ru": "дуть (повтор для группы)"},
        {"en": ["breed", "bred", "bred"], "_": ["briːd", "bred", "bred"], "ru": "разводить (животных)"},
        {"en": ["cling", "clung", "clung"], "_": ["klɪŋ", "klʌŋ", "klʌŋ"], "ru": "цепляться"},
        {"en": ["come", "came", "come"], "_": ["kʌm", "keɪm", "kʌm"], "ru": "приходить (повтор для группы)"},
        {
            "en": ["dwell", "dwelt/dwelled", "dwelt/dwelled"],
            "_": ["dwel", "dwelt", "dwelt"],
            "ru": "обитать, проживать"
        },
        {"en": ["feed", "fed", "fed"], "_": ["fiːd", "fed", "fed"], "ru": "кормить (повтор для группы)"},
        {"en": ["feel", "felt", "felt"], "_": ["fiːl", "felt", "felt"], "ru": "чувствовать (повтор для группы)"},
        {"en": ["fling", "flung", "flung"], "_": ["flɪŋ", "flʌŋ", "flʌŋ"], "ru": "швырять, бросать"},
        {
            "en": ["forbear", "forbore", "forborne"],
            "_": ["fɔːrˈbeər", "fɔːrˈbɔːr", "fɔːrˈbɔːrn"],
            "ru": "воздерживаться"
        },
        {
            "en": ["forecast", "forecast/forecasted", "forecast/forecasted"],
            "_": ["ˈfɔː.kɑːst", "ˈfɔː.kɑːst", "ˈfɔː.kɑːst"],
            "ru": "прогнозировать"
        },
        {"en": ["foresee", "foresaw", "foreseen"], "_": ["fɔːrˈsiː", "fɔːrˈsɔː", "fɔːrˈsiːn"], "ru": "предвидеть"},
        {
            "en": ["foretell", "foretold", "foretold"],
            "_": ["fɔːrˈtel", "fɔːrˈtəʊld", "fɔːrˈtəʊld"],
            "ru": "предсказывать"
        },
        {
            "en": ["forgive", "forgave", "forgiven"],
            "_": ["fərˈɡɪv", "fərˈɡeɪv", "fərˈɡɪv.ən"],
            "ru": "прощать (повтор для группы)"
        },
        {
            "en": ["forsake", "forsook", "forsaken"],
            "_": ["fərˈseɪk", "fərˈsʊk", "fərˈseɪ.kən"],
            "ru": "покидать, оставлять"
        },
        {"en": ["grind", "ground", "ground"], "_": ["ɡraɪnd", "ɡraʊnd", "ɡraʊnd"], "ru": "молоть, точить"},
        {
            "en": ["kneel", "knelt/kneeled", "knelt/kneeled"],
            "_": ["niːl", "nelt", "nelt"],
            "ru": "становиться на колени"
        },
        {"en": ["knit", "knit/knitted", "knit/knitted"], "_": ["nɪt", "nɪt", "nɪt"], "ru": "вязать"},
        {"en": ["lay", "laid", "laid"], "_": ["leɪ", "leɪd", "leɪd"], "ru": "класть, стелить (повтор для группы)"},
        {"en": ["leap", "leapt/leaped", "leapt/leaped"], "_": ["liːp", "lept", "lept"], "ru": "прыгать"},
        {"en": ["lie (лгать)", "lied", "lied"], "_": ["laɪ", "laɪd", "laɪd"], "ru": "лгать (правильный глагол!)"},
        {
            "en": ["light", "lit/lighted", "lit/lighted"],
            "_": ["laɪt", "lɪt", "lɪt"],
            "ru": "зажигать (повтор для группы)"
        },
        {"en": ["mean", "meant", "meant"], "_": ["miːn", "ment", "ment"], "ru": "значить (повтор для группы)"},
        {"en": ["mow", "mowed", "mown/mowed"], "_": ["məʊ", "məʊd", "məʊn"], "ru": "косить (траву)"},
        {
            "en": ["overcome", "overcame", "overcome"],
            "_": ["ˌəʊ.vərˈkʌm", "ˌəʊ.vərˈkeɪm", "ˌəʊ.vərˈkʌm"],
            "ru": "преодолевать"
        },
        {
            "en": ["override", "overrode", "overridden"],
            "_": ["ˌəʊ.vərˈraɪd", "ˌəʊ.vərˈrəʊd", "ˌəʊ.vərˈrɪd.ən"],
            "ru": "отменять (решение)"
        },
        {"en": ["pay", "paid", "paid"], "_": ["peɪ", "peɪd", "peɪd"], "ru": "платить (повтор для группы)"},
        {"en": ["prove", "proved", "proven/proved"], "_": ["pruːv", "pruːvd", "ˈpruː.vən"], "ru": "доказывать"},
        {"en": ["rid", "rid/ridded", "rid/ridded"], "_": ["rɪd", "rɪd", "rɪd"], "ru": "избавлять"},
        {"en": ["sew", "sewed", "sewn/sewed"], "_": ["səʊ", "səʊd", "səʊn"], "ru": "шить"},
        {"en": ["shear", "sheared", "shorn/sheared"], "_": ["ʃɪər", "ʃɪərd", "ʃɔːrn"], "ru": "стричь (овец)"},
        {"en": ["sow", "sowed", "sown/sowed"], "_": ["səʊ", "səʊd", "səʊn"], "ru": "сеять"},
        {
            "en": ["strew", "strewed", "strewn/strewed"],
            "_": ["struː", "struːd", "struːn"],
            "ru": "разбрасывать, устилать"
        },
        {"en": ["stride", "strode", "stridden"], "_": ["straɪd", "strəʊd", "ˈstrɪd.ən"], "ru": "шагать"},
        {"en": ["strike", "struck", "struck"], "_": ["straɪk", "strʌk", "strʌk"], "ru": "ударять (повтор для группы)"},
        {"en": ["string", "strung", "strung"], "_": ["strɪŋ", "strʌŋ", "strʌŋ"], "ru": "нанизывать"},
        {
            "en": ["strive", "strove", "striven"],
            "_": ["straɪv", "strəʊv", "ˈstrɪv.ən"],
            "ru": "стремиться (повтор для группы)"
        },
        {"en": ["swear", "swore", "sworn"], "_": ["sweər", "swɔːr", "swɔːrn"], "ru": "клясться (повтор для группы)"},
        {"en": ["sweat", "sweat/sweated", "sweat/sweated"], "_": ["swet", "swet", "swet"], "ru": "потеть"},
        {"en": ["swell", "swelled", "swollen/swelled"], "_": ["swel", "sweld", "ˈswəʊ.lən"], "ru": "опухать"},
        {
            "en": ["thrive", "thrived/throve", "thrived/thriven"],
            "_": ["θraɪv", "θrəʊv", "ˈθrɪv.ən"],
            "ru": "процветать"
        },
        {"en": ["tread", "trod", "trodden/trod"], "_": ["tred", "trɒd", "ˈtrɒd.ən"], "ru": "ступать"},
        {
            "en": ["undergo", "underwent", "undergone"],
            "_": ["ˌʌn.dərˈɡəʊ", "ˌʌn.dərˈwent", "ˌʌn.dərˈɡɒn"],
            "ru": "подвергаться"
        },
        {
            "en": ["undertake", "undertook", "undertaken"],
            "_": ["ˌʌn.dərˈteɪk", "ˌʌn.dərˈtʊk", "ˌʌn.dərˈteɪ.kən"],
            "ru": "предпринимать"
        },
        {"en": ["weep", "wept", "wept"], "_": ["wiːp", "wept", "wept"], "ru": "плакать"},
        {"en": ["wet", "wet/wetted", "wet/wetted"], "_": ["wet", "wet", "wet"], "ru": "мочить"},
        {"en": ["withhold", "withheld", "withheld"], "_": ["wɪðˈhəʊld", "wɪðˈheld", "wɪðˈheld"], "ru": "удерживать"},
        {
            "en": ["withstand", "withstood", "withstood"],
            "_": ["wɪðˈstænd", "wɪðˈstʊd", "wɪðˈstʊd"],
            "ru": "выдерживать"
        },
        {"en": ["wring", "wrung", "wrung"], "_": ["rɪŋ", "rʌŋ", "rʌŋ"], "ru": "выжимать, скручивать"}]
];